version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: your_pg_user
      POSTGRES_PASSWORD: your_pg_password
      POSTGRES_DB: your_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U your_pg_user -d your_database']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
