version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      song_db:
        condition: service_healthy

  song_db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: song_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d song_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
