services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: StudyLink
      DB_PORT: 5433
    depends_on:
      StudyLink:
        condition: service_healthy

  StudyLink:
    image: postgres:15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: SLAdmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: StudyLink
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d StudyLink']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
