services:
  db:
    image: postgres:latest
    container_name: project_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'

  backend:
    build:
      context: ./backend
    container_name: project_backend
    env_file: .env
    depends_on:
      - db
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./frontend
    container_name: project_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
